version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      python:
        patterns:
          - "*"
        exclude-patterns:
          - "pyinstaller"

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      gitsubmodule:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/ci"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      docker:
        patterns:
          - "*"
    ignore:
      - dependency-name: "docker/library/almalinux"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
