pull_request_rules:
  - name: approve dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE

  # For salt-formula or pyinstaller updates, trigger codebuild, merge on codebuild status
  - name: write issue comment to start codebuild job
    conditions:
      - author=dependabot[bot]
      - and:
          - "#approved-reviews-by>=1"
          - or:
              - label=submodules
              - title~=(?i).*pyinstaller.*
    actions:
      comment:
        message: go codebuild go

  - name: merge dependabot submodule or pyinstaller pull requests with approval and codebuild success
    conditions:
      - author=dependabot[bot]
      - or:
          - label=submodules
          - title~=(?i).*pyinstaller.*
      - status-success=codebuild/default/pr
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

  # For regular dependabot pr, automatically merge on approve
  - name: merge dependabot pull requests that are not pyinstaller and not submodules
    conditions:
      - author=dependabot[bot]
      - "#approved-reviews-by>=1"
      - label!=submodules
      - -title~=(?i).*pyinstaller.*
    actions:
      merge:
        method: merge
