pull_request_rules:
  # For salt-formula or pyinstaller updates, trigger codebuild, merge on codebuild status
  - name: Trigger builds for salt-formula or pyinstaller updates
    conditions:
      - and:
          - author=dependabot[bot]
          - or:
              - label=submodules
              - title~=(?i).*pyinstaller.*
    actions:
      review:
        type: APPROVE
        message: /build

  - name: Merge salt-formula or pyinstaller updates
    conditions:
      - and:
          - author=dependabot[bot]
          - "#approved-reviews-by>=1"
          - or:
              - label=submodules
              - title~=(?i).*pyinstaller.*
          # Must pass codebuild jobs before merge
          - check-success = "test-source (rhel8)"
          - check-success = "test-source (rhel9)"
          - check-success = "test-source (win16)"
          - check-success = "test-source (win19)"
          - check-success = "test-source (win22)"
          - check-success = "test-standalone (rhel8)"
          - check-success = "test-standalone (rhel9)"
          - check-success = "test-standalone (win16)"
          - check-success = "test-standalone (win19)"
          - check-success = "test-standalone (win22)"
    actions:
      merge:
        method: merge

  # For regular dependabot pr, approve and merge after branch protection checks
  - name: Approve dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - label!=submodules
      - -title~=(?i).*pyinstaller.*
    actions:
      review:
        type: APPROVE

  - name: Merge dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - "#approved-reviews-by>=1"
      - label!=submodules
      - -title~=(?i).*pyinstaller.*
    actions:
      merge:
        method: merge
